package com.yunxian.immerse.enumeration;

/**
 * 沉浸类型枚举
 *
 * @author AShuai
 * @email ls1110924@gmail.com
 * @date 2017/1/30 11:48
 */
public enum ImmerseType {

    NORMAL,

    TRANSLUCENT_STATUSBAR,

    TRANSLUCENT_STATUSBAR_WITH_FULLSCREEN,

    TRANSPARENT_STATUSBAR,

    TRANSPARENT_STATUSBAR_WITH_FULLSCREEN,

    TRANSLUCENT_STATUSBAR_AND_NAVIGATIONBAR,

    TRANSLUCENT_STATUSBAR_AND_NAVIGATIONBAR_WITH_FULLSCREEN,

    TRANSPARENT_STATUSBAR_TRANSLUCENT_NAVIGATIONBAR,

    TRANSPARENT_STATUSBAR_TRANSLUCENT_NAVIGATIONBAR_WITH_FULLSCREEN

}
